version: "3.9"

services:
  db:
    image: postgres:15
    container_name: financial_sync_db
    restart: always
    environment:
      POSTGRES_DB: financial_sync
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow_db:
    image: postgres:15
    container_name: airflow_db
    restart: always
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data
  
  airflow_webserver:
    image: apache/airflow:2.8.1
    container_name: airflow_webserver
    restart: always
    depends_on:
      - airflow_db
      - db
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@airflow_db:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
      AIRFLOW_VAR_AWS_ACCESS_KEY_ID: ${AIRFLOW_VAR_AWS_ACCESS_KEY_ID}
      AIRFLOW_VAR_AWS_SECRET_ACCESS_KEY: ${AIRFLOW_VAR_AWS_SECRET_ACCESS_KEY}
      AIRFLOW_VAR_AWS_BUCKET_NAME: ${AIRFLOW_VAR_AWS_BUCKET_NAME}
      AIRFLOW_VAR_AWS_REGION: ${AIRFLOW_VAR_AWS_REGION}
      PYTHONPATH: /opt/airflow/project
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8080:8080"
    command: bash -c "pip install -r /requirements.txt && airflow webserver"
    volumes:
      - ./dags:/opt/airflow/dags
      - .:/opt/airflow/project
      - ./requirements.txt:/requirements.txt

  airflow_scheduler:
    image: apache/airflow:2.8.1
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - airflow_db
      - db
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@airflow_db:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
      AIRFLOW_VAR_AWS_ACCESS_KEY_ID: ${AIRFLOW_VAR_AWS_ACCESS_KEY_ID}
      AIRFLOW_VAR_AWS_SECRET_ACCESS_KEY: ${AIRFLOW_VAR_AWS_SECRET_ACCESS_KEY}
      AIRFLOW_VAR_AWS_BUCKET_NAME: ${AIRFLOW_VAR_AWS_BUCKET_NAME}
      AIRFLOW_VAR_AWS_REGION: ${AIRFLOW_VAR_AWS_REGION}
      PYTHONPATH: /opt/airflow/project
      DATABASE_URL: ${DATABASE_URL}
    command: bash -c "pip install -r /requirements.txt && airflow scheduler"
    volumes:
      - ./dags:/opt/airflow/dags
      - .:/opt/airflow/project
      - ./requirements.txt:/requirements.txt

volumes:
  postgres_data:
  airflow_postgres_data: