version: "3.9"

services:
  db:
    image: postgres:15
    container_name: financial_sync_db
    restart: always
    environment:
      POSTGRES_DB: financial_sync
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow_db:
    image: postgres:15
    container_name: airflow_db
    restart: always
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data
  
  airflow_webserver:
    image: apache/airflow:2.8.1
    container_name: airflow_webserver
    restart: always
    depends_on:
      - airflow_db
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@airflow_db:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    ports:
      - "8080:8080"
    command: webserver
    volumes:
      - ./dags:/opt/airflow/dags

  airflow_scheduler:
    image: apache/airflow:2.8.1
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - airflow_db
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@airflow_db:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags

volumes:
  postgres_data:
  airflow_postgres_data: